/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import dao.WordDao;
import dao.WordDaoImpl;
import entities.Word;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import utils.SizeUtils;

/**
 *
 * @author USER
 */
public class HomepagePanel extends javax.swing.JPanel {

    private PanelCenter panelCenter;
    
    private JLabel lbWord;
    private JSplitPane splitPane;
    private Set<Map.Entry<String, Word>> words;
    private final String pathToDataFile = getClass().getResource("/documents/Dictionary.txt").getFile();
    private final int maximumWordLength = 200;
    private final Font wordFont = new Font("Tahoma", Font.PLAIN, 16);
    
    public HomepagePanel(JSplitPane splitPane) {
        this.splitPane = splitPane;
        
        WordDao wdao = new WordDaoImpl();
        File file = new File(pathToDataFile);
        Map<String, Word> dictionary = wdao.getWords(file);
        words = dictionary.entrySet();
        
        initComponents();
        initComponentManuallys();
    }
    
    private void initComponentManuallys() {
        panelCenter = new PanelCenter(this);
        
        JLabel tmpLabel = new JLabel("Word");
        int height = (tmpLabel.getPreferredSize().height + 5) * words.size();
        pnWords.setPreferredSize(new Dimension(pnWords.getPreferredSize().width, height));
        
        words.forEach((word) -> {
            lbWord = new JLabel((String) word.getKey());
            lbWord.setPreferredSize(new Dimension(maximumWordLength, lbWord.getPreferredSize().height));
            pnWords.add(lbWord);
            
            setEventLbWord(lbWord, word.getValue());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpWords = new javax.swing.JScrollPane();
        pnWords = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnWords.setMinimumSize(new java.awt.Dimension(100, 100));
        scpWords.setViewportView(pnWords);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpWords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpWords)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnWords;
    private javax.swing.JScrollPane scpWords;
    // End of variables declaration//GEN-END:variables

    private void setEventLbWord(JLabel lbWord, Word wordValue) {
        lbWord.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                panelCenter.getlbWord(lbWord.getText());
                
                Component[] sss = pnWords.getComponents();
                for(Component ss : sss){
                    JLabel s = (JLabel) ss;
                    s.setForeground(Color.BLACK);
                }
                
                lbWord.setForeground(Color.LIGHT_GRAY);
                
                PanelCenter pnCenter = (PanelCenter) splitPane.getRightComponent();
                JScrollPane scpCenterCenter = pnCenter.getScpCenterCenter();
                JEditorPane epWordView = new JEditorPane();
                
                epWordView.setContentType("text/html");
                epWordView.setText(wordValue.toString());
                epWordView.setBounds(0, 0, SizeUtils.getPreWidth(epWordView), SizeUtils.getPreHeight(epWordView));
                epWordView.setEditable(false);
                
                
                scpCenterCenter.setViewportView(epWordView);
                scpCenterCenter.revalidate();
                splitPane.revalidate();
            }
            
        });
    }
}