/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import entities.DictionaryEnum;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author USER
 */
public class SettingPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingPanel
     */
    private PanelLeft pnLeft;
    public SettingPanel(PanelLeft panelLeft) {
        this.pnLeft = panelLeft;
        initComponents();
        initEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLanguageSetting = new javax.swing.JLabel();
        lbWebSearchSetting = new javax.swing.JLabel();
        lbDictionaryKindSetting = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbLanguageSetting.setText("Cài đặt ngôn ngữ ứng dụng");

        lbWebSearchSetting.setText("Cài đặt WebSearch");

        lbDictionaryKindSetting.setText("Cài đặt bộ từ điển ứng dụng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDictionaryKindSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLanguageSetting)
                            .addComponent(lbWebSearchSetting))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLanguageSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbWebSearchSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDictionaryKindSetting)
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbDictionaryKindSetting;
    private javax.swing.JLabel lbLanguageSetting;
    private javax.swing.JLabel lbWebSearchSetting;
    // End of variables declaration//GEN-END:variables

    private void initEvents() {
        //
        lbDictionaryKindSetting.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                lbLanguageSetting.setForeground(Color.BLACK);
                lbWebSearchSetting.setForeground(Color.BLACK);
                lbDictionaryKindSetting.setForeground(Color.LIGHT_GRAY);
                pnLeft.setNewDictionary();
            }
        });
    }
}
