/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import common.LanguageAppEnum;
import common.LanguageEnum;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import utils.TranslatorUtils;

/**
 *
 * @author USER
 */
public class TranslatorPanel extends javax.swing.JPanel {
    private Map<String, String> mapLanguage;
    private final LanguageEnum[] languages = LanguageEnum.values();
    private ComboBoxModel<String> languageModelFrom;
    private ComboBoxModel<String> languageModelTo;
    private LanguageAppEnum languageApp;

    public TranslatorPanel(LanguageAppEnum languageApp) {
        this.languageApp = languageApp;
        initComponents();
        initComponentManuallys();
        initEvents();
    }

    private void initComponentManuallys() {
        initComboboxData();
        btEnter.setText(languageApp.getValue("translate_text"));
    }
    private void initComboboxData() {
        List<String> listLanguages = new ArrayList<>();
        Arrays.stream(languages).forEach(language -> listLanguages.add(language.toString()));

        String[] arrayLanguages = listLanguages.toArray(new String[listLanguages.size()]);

        languageModelFrom = new DefaultComboBoxModel<>(arrayLanguages);
        languageModelTo = new DefaultComboBoxModel<>(arrayLanguages);
        for (int i = 0; i < arrayLanguages.length; i++) {
            if (LanguageEnum.English.toString().equals(arrayLanguages[i])) {
                languageModelFrom.setSelectedItem(languageModelFrom.getElementAt(i));
            }
            if (LanguageEnum.Vietnamese.toString().equals(arrayLanguages[i])) {
                languageModelTo.setSelectedItem(languageModelTo.getElementAt(i));
            }
        }

        cbFrom.setModel(languageModelFrom);
        cbTo.setModel(languageModelTo);
    }

    private void initEvents() {
        initBtEnterEvents();
        initBtSwapEvents();
    }

    private void initBtEnterEvents() {
        mapLanguage = mockMapData();

        btEnter.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                try {
                    taOutput.setText(TranslatorUtils.translate(mapLanguage.get(languageModelFrom.getSelectedItem().toString()),
                            mapLanguage.get(languageModelTo.getSelectedItem().toString()), taInput.getText()));
                } catch (IOException ex) {
                    Logger.getLogger(TranslatorPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void initBtSwapEvents() {
        btSwap.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                String selectedFrom = languageModelFrom.getSelectedItem().toString();
                String selectedTo = languageModelTo.getSelectedItem().toString();
                languageModelFrom.setSelectedItem(selectedTo);
                languageModelTo.setSelectedItem(selectedFrom);
            }

        });
    }

    private Map<String, String> mockMapData() {
        Map<String, String> map = new HashMap<>();
        for (LanguageEnum language : languages) {
            map.put(language.toString(), language.getValue());
        }

        return map;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFrom = new javax.swing.JComboBox<>();
        cbTo = new javax.swing.JComboBox<>();
        btSwap = new javax.swing.JButton();
        btEnter = new javax.swing.JButton();
        scpOutput = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        scpInput = new javax.swing.JScrollPane();
        taInput = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(249, 226, 253));

        cbFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        cbFrom.setFocusable(false);

        cbTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        cbTo.setFocusable(false);

        btSwap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icon-swap-16px.png.png"))); // NOI18N
        btSwap.setBorderPainted(false);
        btSwap.setContentAreaFilled(false);
        btSwap.setFocusPainted(false);

        btEnter.setBackground(new java.awt.Color(204, 204, 255));
        btEnter.setText("Translate");
        btEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btEnter.setFocusPainted(false);

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        taOutput.setRows(5);
        taOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        scpOutput.setViewportView(taOutput);

        taInput.setColumns(20);
        taInput.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        taInput.setRows(5);
        taInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        taInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        scpInput.setViewportView(taInput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSwap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addComponent(scpOutput)
                    .addComponent(scpInput, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSwap)
                    .addComponent(btEnter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btEnter, btSwap, cbFrom, cbTo});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnter;
    private javax.swing.JButton btSwap;
    private javax.swing.JComboBox<String> cbFrom;
    private javax.swing.JComboBox<String> cbTo;
    private javax.swing.JScrollPane scpInput;
    private javax.swing.JScrollPane scpOutput;
    private javax.swing.JTextArea taInput;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
